name : Event Details
on: issues
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Output Events
        run: echo "${{toJSON(github)}}"
